const weatherCode = [
  { weatherCode: 113, weather: "맑음", keyword: "sunny" },
  { weatherCode: 116, weather: "맑음", keyword: "sunny" },
  { weatherCode: 119, weather: "구름", keyword: "cloud" },
  { weatherCode: 122, weather: "흐림", keyword: "cloud" },
  { weatherCode: 143, weather: "안개", keyword: "cloud" },
  { weatherCode: 176, weather: "비", keyword: "rain" },
  { weatherCode: 179, weather: "눈", keyword: "snow" },
  { weatherCode: 182, weather: "눈", keyword: "snow" },
  { weatherCode: 185, weather: "비", keyword: "rain" },
  { weatherCode: 200, weather: "천둥", keyword: "thunder" },
  { weatherCode: 227, weather: "눈", keyword: "snow" },
  { weatherCode: 230, weather: "눈", keyword: "snow" },
  { weatherCode: 248, weather: "안개", keyword: "cloud" },
  { weatherCode: 260, weather: "안개", keyword: "cloud" },
  { weatherCode: 263, weather: "비", keyword: "rain" },
  { weatherCode: 266, weather: "비", keyword: "rain" },
  { weatherCode: 281, weather: "비", keyword: "rain" },
  { weatherCode: 284, weather: "비", keyword: "rain" },
  { weatherCode: 293, weather: "비", keyword: "rain" },
  { weatherCode: 296, weather: "비", keyword: "rain" },
  { weatherCode: 299, weather: "비", keyword: "rain" },
  { weatherCode: 302, weather: "비", keyword: "rain" },
  { weatherCode: 305, weather: "비", keyword: "rain" },
  { weatherCode: 308, weather: "비", keyword: "rain" },
  { weatherCode: 311, weather: "비", keyword: "rain" },
];

module.exports = weatherCode;
